#pragma config(Sensor, S4,     sonic,          sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(sonic)>10)
	{
		motor[motorB]=50;
		motor[motorC]=50;
	}

	if(SensorValue(sonic)<=10)
	{
		motor[motorB]=-50;
		motor[motorC]=-50;
		wait1Msec(1000);
	}


}
