#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     ultraSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int loops=-0;

while(loops==0)
{

	while(SensorValue(touchSensor)==0)
	{
		motor[motorB]=50;
		motor[motorC]=50;
	}
	if(SensorValue(touchSensor)==1)
	{
		motor[motorB]=0;
		motor[motorC]=0;
		wait1Msec(2000);
	}
	while(SensorValue(touchSensor)==0)
	{
		motor[motorB]=50;
		motor[motorC]=50;
	}
}

}
